version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bopay_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local_network
  fastapi:
    container_name: bopay_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - local_network

volumes:
  pgdata:

networks:
  local_network:
    driver: bridge
  