"""orders_products__name

Revision ID: 521664f18d78
Revises: a1251783b80d
Create Date: 2025-06-04 23:09:46.512531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521664f18d78'
down_revision: Union[str, None] = 'a1251783b80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('orders_products_product_id_fkey'), 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key(op.f('orders_products_product_id_fkey'), 'orders_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders_products', 'name')
    # ### end Alembic commands ###
