"""orders__receipt_status

Revision ID: 5dd30a63903e
Revises: ae9956acd1ba
Create Date: 2025-09-01 18:30:50.560976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd30a63903e'
down_revision: Union[str, None] = 'ae9956acd1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receipt_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_status')
    # ### end Alembic commands ###
