"""orders_products__fks

Revision ID: a1251783b80d
Revises: 5f76761276e0
Create Date: 2025-06-04 21:48:05.040290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1251783b80d'
down_revision: Union[str, None] = '5f76761276e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_products_product_id'), 'orders_products', ['product_id'], unique=False)
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_index(op.f('ix_orders_products_product_id'), table_name='orders_products')
    # ### end Alembic commands ###
