"""empty message

Revision ID: aa0ccd4ff31d
Revises: 521664f18d78
Create Date: 2025-06-05 19:19:18.855687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0ccd4ff31d'
down_revision: Union[str, None] = '521664f18d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_products_product_id_fkey'), 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key(op.f('orders_products_product_id_fkey'), 'orders_products', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
