"""orders__receipt_id

Revision ID: ae9956acd1ba
Revises: ed7c5b781570
Create Date: 2025-07-08 17:41:13.636127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9956acd1ba'
down_revision: Union[str, None] = 'ed7c5b781570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receipt_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('orders_payment_id_key'), 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('orders_payment_id_key'), 'orders', ['payment_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('orders', 'receipt_id')
    # ### end Alembic commands ###
