"""empty message

Revision ID: c84903d194e2
Revises: 3d363fcdc767
Create Date: 2025-06-05 19:27:46.891833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84903d194e2'
down_revision: Union[str, None] = '3d363fcdc767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_products', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders_products', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_products', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders_products', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
