"""empty message

Revision ID: e877f3bc426b
Revises: aa0ccd4ff31d
Create Date: 2025-06-05 19:24:23.623149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e877f3bc426b'
down_revision: Union[str, None] = 'aa0ccd4ff31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_products_order_id_fkey'), 'orders_products', type_='foreignkey')
    op.drop_constraint(op.f('orders_products_product_id_fkey'), 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'orders_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key(op.f('orders_products_product_id_fkey'), 'orders_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_products_order_id_fkey'), 'orders_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
